apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  template:
    metadata:
      name: backend
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: docker.io/ibmcom/pause-ppc64le:3.1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always