apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifetime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifetime
  template:
    metadata:
      name: lifetime
      labels:
        app: lifetime
    spec:
      containers:
      - name: lifetime
        image: docker.io/ibmcom/pause-ppc64le:3.1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always