apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbalanced
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unbalanced
  template:
    metadata:
      name: unbalanced
      labels:
        app: unbalanced
    spec:
      topologySpreadConstraints:
        - maxSkew: 1 
          topologyKey: topology.kubernetes.io/zone 
          whenUnsatisfiable: ScheduleAnyway 
          labelSelector: 
          matchLabels:
            app: unbalanced 
      containers:
      - name: unbalanced
        image: docker.io/ibmcom/pause-ppc64le:3.1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      restartPolicy: Always